export enum PageIds {
  BLUEPRINT = 'blueprint',
  EXAMPLES = 'examples',
  HOME = 'home',
  INTRODUCTION = 'introduction',
  MODULES_COMMANDS = 'commands',
  MODULES_CONTAINERS = 'containers',
  MODULES_DATA = 'data',
  MODULES_FACADES = 'facades',
  MODULES_PRESENTATIONAL = 'presentational',
  MODULESQUERIES = 'queries',
  OVERVIEW = 'overview',
  PRINCIPLES_DECLARATIVE = 'declarative',
  PRINCIPLES_FRP = 'funcitonal-reactive-programming',
  PRINCIPLES_PROJECTION = 'projection',
  PRINCIPLES_UNIDIRECTIONAL_DATA_FLOW = 'unidirectional-data-flow',
  RESOURCES = 'resources',
  RESOURCES_DETAIL = 'resources-detail',
}
